org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

libVersion=d1eeb8a34f

# Can be music, tracker or lyrics
extType=misc
extId=echodown
extClass=EDExtension

extIconUrl=https://cdn-images.dzcdn.net/images/cover/00e78b6d932527f79d2df3f4f694510b/264x264-000000-80-0-0.jpg
extName=EchoDown
extDescription=EchoDown Extension for Echo.

extAuthor=Luftnos
extAuthorUrl=https://github.com/LuftVerbot

extRepoUrl=https://github.com/LuftVerbot/echo-echodown-extension
extUpdateUrl=https://api.github.com/repos/LuftVerbot/echo-echodown-extension/releases/latest